### PR TITLE
Add a Wireshark plugin generator

### PR DESCRIPTION
**Pull request by bbannier**

### CODE REVIEW

**Comment by bbannier** [comment]
I have rebased this branch on #523 so we can show source offsets for parsed data as well.

Screen Shot 2020-10-02 at 10 38 03 PM

**Comment by bbannier** [comment]
To run this on macos I installed the the wireshark package with

```.sh
brew install wireshark           # command line tools
brew cask install wireshark  # app
```

and build the dissector from the wireshark folder with

```.sh
 PATH=~/src/spicy/build/bin:$PATH ./make_plugin.py \
    ../spicy/lib/protocols/tftp.spicy \
    --parser TFTP::Packet \
    --plugin_version 0.0.1 \
    --plugin_want_major 3 --plugin_want_minor=3 \
    --wireshark_include_dir=/usr/local/Cellar/wireshark/3.2.7/include/wireshark \
    --wireshark_library_dir=/usr/local/Cellar/wireshark/3.2.7/lib  \
    --output spicy.so
```

The output file `spicy.so` can then be dropped into the app's library folder:
```.sh
cp cp spicy.so /Applications/Wireshark.app/Contents/PlugIns/wireshark/3-2/epan
```

**Comment by rsmmr** [comment]
Updated screenshot with `%print` hooks:

Screen Shot 2020-10-14 at 13 04 07

**Comment by bbannier** [comment]
Since we do not want to merge this code in its current form, closing this PR for now. Further work is tracked in #549.

**Pull request closed without merging**
