### PR TITLE
Fix a few remaining uses of `unsafeEnd`.

### PR DESCRIPTION
**Pull request by bbannier**

### CODE REVIEW

**Comment by bbannier** [comment]
Similar to #1345, `unsafeEnd` again showed up as a bottleneck (I had initially missed this function since it is in a template function). There are still other uses of `unsafeEnd` in the code base which I probably also need to look at more carefully.

**Review by rsmmr — COMMENTED** [review]
I need to go through in more detail but quick note: I'm not sure that it's good to change all of these: the reason that we have `UnsafeIterator` in the 1st place is to avoid unnecessary bounds checking that `SafeIterator` would do. So while switching from safe to unsafe helps with the issue we found the other day, it adds overhead when dereferencing the iterator. It would be ideal if we could get the best of both worlds: a non-checking iterator that doesn't have that original problem for `.unsafeEnd()`

**Comment by bbannier** [comment]
>  It would be ideal if we could get the best of both worlds: a non-checking iterator that doesn't have that original problem for `.unsafeEnd()`

I agree, the current situation is not good since it is very hard to tell which API would be better for a certain situation. From a quick check, it looks like currently it is not straight-forward to make `unsafeEnd` fast since the underlying implementation uses a linked list. I filed #1347 to make use something slower there instead.

**Comment by bbannier** [comment]
Closing this in favor of #1374.

**Pull request closed without merging**
